"""crear conversaciones chatbot

Revision ID: 1a7223a78dae
Revises: a6002d6c9206
Create Date: 2026-09-04 19:06:24.637295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a7223a78dae'
down_revision: Union[str, Sequence[str], None] = 'a6002d6c9206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversaciones_chatbot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('esperando_documento', sa.Boolean(), nullable=False),
    sa.Column('esperando_descripcion_soporte', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_chatbot_cliente_id'), 'conversaciones_chatbot', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_chatbot_empresa_id'), 'conversaciones_chatbot', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_chatbot_telefono'), 'conversaciones_chatbot', ['telefono'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversaciones_chatbot_telefono'), table_name='conversaciones_chatbot')
    op.drop_index(op.f('ix_conversaciones_chatbot_empresa_id'), table_name='conversaciones_chatbot')
    op.drop_index(op.f('ix_conversaciones_chatbot_cliente_id'), table_name='conversaciones_chatbot')
    op.drop_table('conversaciones_chatbot')
    # ### end Alembic commands ###