"""agregar factura id a pagos

Revision ID: 1c4d043c9d75
Revises: 1d3ac4b39758
Create Date: 2026-09-01 20:22:44.844536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1c4d043c9d75'
down_revision: Union[str, Sequence[str], None] = '1d3ac4b39758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('factura_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_pagos_factura_id'), 'pagos', ['factura_id'], unique=False)
    op.create_foreign_key(None, 'pagos', 'facturas', ['factura_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagos', type_='foreignkey')
    op.drop_index(op.f('ix_pagos_factura_id'), table_name='pagos')
    op.drop_column('pagos', 'factura_id')
    # ### end Alembic commands ###