"""agregar referencia de pago a facturas

Revision ID: 1d3ac4b39758
Revises: c254d806b376
Create Date: 2026-09-01 10:51:05.154040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d3ac4b39758'
down_revision: Union[str, Sequence[str], None] = 'c254d806b376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('referencia_pago', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_facturas_referencia_pago'), 'facturas', ['referencia_pago'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_referencia_pago'), table_name='facturas')
    op.drop_column('facturas', 'referencia_pago')
    # ### end Alembic commands ###