"""agregar datos de contratacion al chatbot

Revision ID: 3bb104a9ca7e
Revises: 1a7223a78dae
Create Date: 2026-09-22 23:38:32.350746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bb104a9ca7e'
down_revision: Union[str, Sequence[str], None] = '1a7223a78dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'conversaciones_chatbot',
    sa.Column(
        'esperando_datos_contratacion',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
)
    op.add_column('conversaciones_chatbot', sa.Column('paso_contratacion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('conversaciones_chatbot', sa.Column('nombre_contratacion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('conversaciones_chatbot', sa.Column('documento_contratacion', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('conversaciones_chatbot', sa.Column('direccion_contratacion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('conversaciones_chatbot', sa.Column('plan_contratacion', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversaciones_chatbot', 'plan_contratacion')
    op.drop_column('conversaciones_chatbot', 'direccion_contratacion')
    op.drop_column('conversaciones_chatbot', 'documento_contratacion')
    op.drop_column('conversaciones_chatbot', 'nombre_contratacion')
    op.drop_column('conversaciones_chatbot', 'paso_contratacion')
    op.drop_column('conversaciones_chatbot', 'esperando_datos_contratacion')
    # ### end Alembic commands ###