"""Crear clientes planes y servicios

Revision ID: c254d806b376
Revises: b9e245143583
Create Date: 2026-08-10 22:59:02.873582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c254d806b376'
down_revision: Union[str, Sequence[str], None] = 'b9e245143583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('barrio', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('referencia_direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=False)
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_clientes_estado'), 'clientes', ['estado'], unique=False)
    op.create_table('planes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('velocidad_bajada', sa.Integer(), nullable=False),
    sa.Column('velocidad_subida', sa.Integer(), nullable=False),
    sa.Column('precio_mensual', sa.Float(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_empresa_id'), 'planes', ['empresa_id'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('usuario_pppoe', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('suspendido', sa.Boolean(), nullable=False),
    sa.Column('motivo_suspension', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_cliente_id'), 'servicios', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_servicios_empresa_id'), 'servicios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_servicios_estado'), 'servicios', ['estado'], unique=False)
    op.create_index(op.f('ix_servicios_plan_id'), 'servicios', ['plan_id'], unique=False)
    op.create_index(op.f('ix_servicios_usuario_pppoe'), 'servicios', ['usuario_pppoe'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicios_usuario_pppoe'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_plan_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_estado'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_empresa_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_cliente_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_planes_empresa_id'), table_name='planes')
    op.drop_table('planes')
    op.drop_index(op.f('ix_clientes_estado'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###