"""crear evidencias soporte

Revision ID: ea7438045f6f
Revises: 3bb104a9ca7e
Create Date: 2026-09-24 11:12:00.443558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ea7438045f6f'
down_revision: Union[str, Sequence[str], None] = '3bb104a9ca7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###