"""crear comprobantes de pago

Revision ID: fccef8f8befe
Revises: ea7438045f6f
Create Date: 2026-09-24 21:07:32.715070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'fccef8f8befe'
down_revision: Union[str, Sequence[str], None] = 'ea7438045f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###